development:
  email:
    server: smtp.gmail.com
    port: 587
    domain: gmail.com
    authentication: plain
    username: loseitwithus@gmail.com
    password: loseitwithus
    contact_recipient: loseitwithus@gmail.com
production:
  email:
      server: smtp.gmail.com
      port: 587
      domain: gmail.com
      authentication: plain
      username: loseitwithus@gmail.com
      password: loseitwithus
      contact_recipient: loseitwithus@gmail.com