require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DietsController do

  def mock_diet(stubs={})
    @mock_diet ||= mock_model(Diet, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all diets as @diets" do
      Diet.stub(:all) { [mock_diet] }
      get :index
      assigns(:diets).should eq([mock_diet])
    end
  end

  describe "GET show" do
    it "assigns the requested diet as @diet" do
      Diet.stub(:find).with("37") { mock_diet }
      get :show, :id => "37"
      assigns(:diet).should be(mock_diet)
    end
  end

  describe "GET new" do
    it "assigns a new diet as @diet" do
      Diet.stub(:new) { mock_diet }
      get :new
      assigns(:diet).should be(mock_diet)
    end
  end

  describe "GET edit" do
    it "assigns the requested diet as @diet" do
      Diet.stub(:find).with("37") { mock_diet }
      get :edit, :id => "37"
      assigns(:diet).should be(mock_diet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created diet as @diet" do
        Diet.stub(:new).with({'these' => 'params'}) { mock_diet(:save => true) }
        post :create, :diet => {'these' => 'params'}
        assigns(:diet).should be(mock_diet)
      end

      it "redirects to the created diet" do
        Diet.stub(:new) { mock_diet(:save => true) }
        post :create, :diet => {}
        response.should redirect_to(diet_url(mock_diet))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diet as @diet" do
        Diet.stub(:new).with({'these' => 'params'}) { mock_diet(:save => false) }
        post :create, :diet => {'these' => 'params'}
        assigns(:diet).should be(mock_diet)
      end

      it "re-renders the 'new' template" do
        Diet.stub(:new) { mock_diet(:save => false) }
        post :create, :diet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diet" do
        Diet.stub(:find).with("37") { mock_diet }
        mock_diet.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :diet => {'these' => 'params'}
      end

      it "assigns the requested diet as @diet" do
        Diet.stub(:find) { mock_diet(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:diet).should be(mock_diet)
      end

      it "redirects to the diet" do
        Diet.stub(:find) { mock_diet(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(diet_url(mock_diet))
      end
    end

    describe "with invalid params" do
      it "assigns the diet as @diet" do
        Diet.stub(:find) { mock_diet(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:diet).should be(mock_diet)
      end

      it "re-renders the 'edit' template" do
        Diet.stub(:find) { mock_diet(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diet" do
      Diet.stub(:find).with("37") { mock_diet }
      mock_diet.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the diets list" do
      Diet.stub(:find) { mock_diet }
      delete :destroy, :id => "1"
      response.should redirect_to(diets_url)
    end
  end

end
